id: IA83EE6D2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:36:57+00:00'
last_modified: '2022-06-07T15:09:47.515506+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30532
  title: བཀའ་འགྱུར། ༼སྡེ་དགེ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    329B:
      image_group_id: I6348
      title: ''
      total_pages: 624
      order: 1
      base_file: 329B.txt
    12D4:
      image_group_id: I6349
      title: ''
      total_pages: 636
      order: 2
      base_file: 12D4.txt
    4B9F:
      image_group_id: I6350
      title: ''
      total_pages: 588
      order: 3
      base_file: 4B9F.txt
    01E9:
      image_group_id: I6351
      title: ''
      total_pages: 606
      order: 4
      base_file: 01E9.txt
    '1784':
      image_group_id: I6352
      title: ''
      total_pages: 590
      order: 5
      base_file: 1784.txt
    '4384':
      image_group_id: I6353
      title: ''
      total_pages: 576
      order: 6
      base_file: 4384.txt
    DD39:
      image_group_id: I6354
      title: ''
      total_pages: 576
      order: 7
      base_file: DD39.txt
    D60E:
      image_group_id: I6355
      title: ''
      total_pages: 540
      order: 8
      base_file: D60E.txt
    555E:
      image_group_id: I6356
      title: ''
      total_pages: 658
      order: 9
      base_file: 555E.txt
    FEF3:
      image_group_id: I6357
      title: ''
      total_pages: 622
      order: 10
      base_file: FEF3.txt
    FF10:
      image_group_id: I6358
      title: ''
      total_pages: 668
      order: 11
      base_file: FF10.txt
    4B61:
      image_group_id: I6359
      title: ''
      total_pages: 606
      order: 12
      base_file: 4B61.txt
    4F4F:
      image_group_id: I6360
      title: ''
      total_pages: 628
      order: 13
      base_file: 4F4F.txt
    FCC0:
      image_group_id: I6361
      title: ''
      total_pages: 790
      order: 14
      base_file: FCC0.txt
    88AD:
      image_group_id: I6362
      title: ''
      total_pages: 806
      order: 15
      base_file: 88AD.txt
    C279:
      image_group_id: I6363
      title: ''
      total_pages: 790
      order: 16
      base_file: C279.txt
    436A:
      image_group_id: I6364
      title: ''
      total_pages: 764
      order: 17
      base_file: 436A.txt
    EDF9:
      image_group_id: I6365
      title: ''
      total_pages: 790
      order: 18
      base_file: EDF9.txt
    D449:
      image_group_id: I6366
      title: ''
      total_pages: 764
      order: 19
      base_file: D449.txt
    6DA6:
      image_group_id: I6367
      title: ''
      total_pages: 798
      order: 20
      base_file: 6DA6.txt
    3ED3:
      image_group_id: I6368
      title: ''
      total_pages: 800
      order: 21
      base_file: 3ED3.txt
    A0B5:
      image_group_id: I6369
      title: ''
      total_pages: 770
      order: 22
      base_file: A0B5.txt
    3F85:
      image_group_id: I6370
      title: ''
      total_pages: 776
      order: 23
      base_file: 3F85.txt
    990B:
      image_group_id: I6371
      title: ''
      total_pages: 824
      order: 24
      base_file: 990B.txt
    B4C8:
      image_group_id: I6372
      title: ''
      total_pages: 792
      order: 25
      base_file: B4C8.txt
    6D55:
      image_group_id: I6373
      title: ''
      total_pages: 766
      order: 26
      base_file: 6D55.txt
    F424:
      image_group_id: I6374
      title: ''
      total_pages: 788
      order: 27
      base_file: F424.txt
    4B2C:
      image_group_id: I6375
      title: ''
      total_pages: 764
      order: 28
      base_file: 4B2C.txt
    D604:
      image_group_id: I6376
      title: ''
      total_pages: 602
      order: 29
      base_file: D604.txt
    BACB:
      image_group_id: I6377
      title: ''
      total_pages: 610
      order: 30
      base_file: BACB.txt
    0830:
      image_group_id: I6378
      title: ''
      total_pages: 596
      order: 31
      base_file: 0830.txt
    A621:
      image_group_id: I6379
      title: ''
      total_pages: 614
      order: 32
      base_file: A621.txt
    4AD7:
      image_group_id: I6380
      title: ''
      total_pages: 572
      order: 33
      base_file: 4AD7.txt
    9FC1:
      image_group_id: I6381
      title: ''
      total_pages: 570
      order: 34
      base_file: 9FC1.txt
    A454:
      image_group_id: I6382
      title: ''
      total_pages: 788
      order: 35
      base_file: A454.txt
    643A:
      image_group_id: I6383
      title: ''
      total_pages: 796
      order: 36
      base_file: 643A.txt
    B0BD:
      image_group_id: I6384
      title: ''
      total_pages: 792
      order: 37
      base_file: B0BD.txt
    9AD7:
      image_group_id: I6385
      title: ''
      total_pages: 726
      order: 38
      base_file: 9AD7.txt
    C456:
      image_group_id: I6386
      title: ''
      total_pages: 542
      order: 39
      base_file: C456.txt
    '2225':
      image_group_id: I6387
      title: ''
      total_pages: 590
      order: 40
      base_file: 2225.txt
    F29D:
      image_group_id: I6388
      title: ''
      total_pages: 598
      order: 41
      base_file: F29D.txt
    E470:
      image_group_id: I6389
      title: ''
      total_pages: 576
      order: 42
      base_file: E470.txt
    55AA:
      image_group_id: I6390
      title: ''
      total_pages: 618
      order: 43
      base_file: 55AA.txt
    C632:
      image_group_id: I6391
      title: ''
      total_pages: 600
      order: 44
      base_file: C632.txt
    BB03:
      image_group_id: I6392
      title: ''
      total_pages: 682
      order: 45
      base_file: BB03.txt
    '5546':
      image_group_id: I6393
      title: ''
      total_pages: 558
      order: 46
      base_file: 5546.txt
    8B55:
      image_group_id: I6394
      title: ''
      total_pages: 612
      order: 47
      base_file: 8B55.txt
    0A18:
      image_group_id: I6395
      title: ''
      total_pages: 578
      order: 48
      base_file: 0A18.txt
    E1EA:
      image_group_id: I6396
      title: ''
      total_pages: 586
      order: 49
      base_file: E1EA.txt
    A45D:
      image_group_id: I6397
      title: ''
      total_pages: 594
      order: 50
      base_file: A45D.txt
    B03B:
      image_group_id: I6398
      title: ''
      total_pages: 592
      order: 51
      base_file: B03B.txt
    DDBF:
      image_group_id: I6399
      title: ''
      total_pages: 688
      order: 52
      base_file: DDBF.txt
    8ED3:
      image_group_id: I6400
      title: ''
      total_pages: 682
      order: 53
      base_file: 8ED3.txt
    86BD:
      image_group_id: I6401
      title: ''
      total_pages: 594
      order: 54
      base_file: 86BD.txt
    '8624':
      image_group_id: I6402
      title: ''
      total_pages: 634
      order: 55
      base_file: 8624.txt
    6BB7:
      image_group_id: I6403
      title: ''
      total_pages: 602
      order: 56
      base_file: 6BB7.txt
    6A66:
      image_group_id: I6404
      title: ''
      total_pages: 690
      order: 57
      base_file: 6A66.txt
    5F06:
      image_group_id: I6405
      title: ''
      total_pages: 640
      order: 58
      base_file: 5F06.txt
    EDD3:
      image_group_id: I6406
      title: ''
      total_pages: 630
      order: 59
      base_file: EDD3.txt
    '5755':
      image_group_id: I6407
      title: ''
      total_pages: 594
      order: 60
      base_file: 5755.txt
    E601:
      image_group_id: I6408
      title: ''
      total_pages: 618
      order: 61
      base_file: E601.txt
    0BE6:
      image_group_id: I6409
      title: ''
      total_pages: 616
      order: 62
      base_file: 0BE6.txt
    B15D:
      image_group_id: I6410
      title: ''
      total_pages: 596
      order: 63
      base_file: B15D.txt
    FF92:
      image_group_id: I6411
      title: ''
      total_pages: 600
      order: 64
      base_file: FF92.txt
    6B46:
      image_group_id: I6412
      title: ''
      total_pages: 614
      order: 65
      base_file: 6B46.txt
    62BB:
      image_group_id: I6413
      title: ''
      total_pages: 622
      order: 66
      base_file: 62BB.txt
    '5375':
      image_group_id: I6414
      title: ''
      total_pages: 640
      order: 67
      base_file: 5375.txt
    '7034':
      image_group_id: I6415
      title: ''
      total_pages: 638
      order: 68
      base_file: 7034.txt
    0A1B:
      image_group_id: I6416
      title: ''
      total_pages: 616
      order: 69
      base_file: 0A1B.txt
    '0057':
      image_group_id: I6417
      title: ''
      total_pages: 626
      order: 70
      base_file: 0057.txt
    D47E:
      image_group_id: I6418
      title: ''
      total_pages: 612
      order: 71
      base_file: D47E.txt
    '5900':
      image_group_id: I6419
      title: ''
      total_pages: 622
      order: 72
      base_file: 5900.txt
    12B9:
      image_group_id: I6420
      title: ''
      total_pages: 620
      order: 73
      base_file: 12B9.txt
    '4931':
      image_group_id: I6421
      title: ''
      total_pages: 2
      order: 74
      base_file: 4931.txt
    CFCA:
      image_group_id: I6422
      title: ''
      total_pages: 2
      order: 75
      base_file: CFCA.txt
    '5914':
      image_group_id: I6423
      title: ''
      total_pages: 580
      order: 76
      base_file: 5914.txt
    BD0B:
      image_group_id: I6424
      title: ''
      total_pages: 744
      order: 77
      base_file: BD0B.txt
    59F6:
      image_group_id: I6425
      title: ''
      total_pages: 624
      order: 78
      base_file: 59F6.txt
    FDD9:
      image_group_id: I6426
      title: ''
      total_pages: 586
      order: 79
      base_file: FDD9.txt
    628C:
      image_group_id: I6427
      title: ''
      total_pages: 688
      order: 80
      base_file: 628C.txt
    0A19:
      image_group_id: I6428
      title: ''
      total_pages: 620
      order: 81
      base_file: 0A19.txt
    6C3A:
      image_group_id: I6429
      title: ''
      total_pages: 664
      order: 82
      base_file: 6C3A.txt
    E0EA:
      image_group_id: I6430
      title: ''
      total_pages: 676
      order: 83
      base_file: E0EA.txt
    3CE0:
      image_group_id: I6431
      title: ''
      total_pages: 552
      order: 84
      base_file: 3CE0.txt
    '1417':
      image_group_id: I6432
      title: ''
      total_pages: 548
      order: 85
      base_file: 1417.txt
    7B99:
      image_group_id: I6433
      title: ''
      total_pages: 648
      order: 86
      base_file: 7B99.txt
    C32D:
      image_group_id: I6434
      title: ''
      total_pages: 620
      order: 87
      base_file: C32D.txt
    7E77:
      image_group_id: I6435
      title: ''
      total_pages: 704
      order: 88
      base_file: 7E77.txt
    D981:
      image_group_id: I6436
      title: ''
      total_pages: 548
      order: 89
      base_file: D981.txt
    795E:
      image_group_id: I6437
      title: ''
      total_pages: 576
      order: 90
      base_file: 795E.txt
    4E42:
      image_group_id: I6438
      title: ''
      total_pages: 586
      order: 91
      base_file: 4E42.txt
    F74A:
      image_group_id: I6439
      title: ''
      total_pages: 636
      order: 92
      base_file: F74A.txt
    '5650':
      image_group_id: I6440
      title: ''
      total_pages: 626
      order: 93
      base_file: 5650.txt
    3DB1:
      image_group_id: I6441
      title: ''
      total_pages: 540
      order: 94
      base_file: 3DB1.txt
    790B:
      image_group_id: I6442
      title: ''
      total_pages: 592
      order: 95
      base_file: 790B.txt
    D20E:
      image_group_id: I6443
      title: ''
      total_pages: 530
      order: 96
      base_file: D20E.txt
    0469:
      image_group_id: I6444
      title: ''
      total_pages: 716
      order: 97
      base_file: 0469.txt
    DDF7:
      image_group_id: I6445
      title: ''
      total_pages: 630
      order: 98
      base_file: DDF7.txt
    91B8:
      image_group_id: I6446
      title: ''
      total_pages: 0
      order: 99
      base_file: 91B8.txt
    '8446':
      image_group_id: I6447
      title: ''
      total_pages: 568
      order: 100
      base_file: 8446.txt
    DD98:
      image_group_id: I6448
      title: ''
      total_pages: 558
      order: 101
      base_file: DD98.txt
    DB55:
      image_group_id: I6449
      title: ''
      total_pages: 944
      order: 102
      base_file: DB55.txt
    '1746':
      image_group_id: I6450
      title: ''
      total_pages: 344
      order: 103
      base_file: 1746.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
